# Generated by Django 5.2.6 on 2025-09-19 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQCKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('algorithm', models.CharField(max_length=128)),
                ('public_key', models.BinaryField(blank=True, null=True)),
                ('private_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('private_key_retention', models.CharField(choices=[('none', 'Do not store private key'), ('encrypted', 'Store encrypted (admin only)')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqc_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
