# Generated by Django 5.2.6 on 2025-09-19 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(default=list)),
                ('actor_type', models.CharField(choices=[('apt', 'Advanced Persistent Threat'), ('cybercriminal', 'Cybercriminal Group'), ('nation_state', 'Nation State'), ('hacktivist', 'Hacktivist'), ('insider', 'Insider Threat'), ('unknown', 'Unknown')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('motivation', models.TextField(blank=True)),
                ('capabilities', models.JSONField(default=list)),
                ('targets', models.JSONField(default=list)),
                ('ttps', models.JSONField(default=list)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('confidence', models.IntegerField(default=50)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'threat_actors',
            },
        ),
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash_md5', 'MD5 Hash'), ('hash_sha1', 'SHA1 Hash'), ('hash_sha256', 'SHA256 Hash'), ('email', 'Email Address'), ('file_path', 'File Path'), ('registry_key', 'Registry Key'), ('user_agent', 'User Agent'), ('certificate', 'Certificate'), ('mutex', 'Mutex'), ('yara_rule', 'YARA Rule')], max_length=20)),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('botnet', 'Botnet'), ('phishing', 'Phishing'), ('c2', 'Command & Control'), ('apt', 'Advanced Persistent Threat'), ('ransomware', 'Ransomware'), ('trojan', 'Trojan'), ('backdoor', 'Backdoor'), ('exploit', 'Exploit'), ('suspicious', 'Suspicious Activity')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('whitelist', 'Whitelisted')], default='active', max_length=20)),
                ('confidence', models.IntegerField(default=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('tlp', models.CharField(default='white', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'indicators_of_compromise',
            },
        ),
        migrations.CreateModel(
            name='ThreatCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('concluded', 'Concluded'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('targets', models.JSONField(default=list)),
                ('attack_patterns', models.JSONField(default=list)),
                ('malware_families', models.JSONField(default=list)),
                ('confidence', models.IntegerField(default=50)),
                ('metadata', models.JSONField(default=dict)),
                ('iocs', models.ManyToManyField(blank=True, related_name='campaigns', to='threat_intelligence.indicatorofcompromise')),
                ('threat_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threat_intelligence.threatactor')),
            ],
            options={
                'db_table': 'threat_campaigns',
            },
        ),
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feed_type', models.CharField(choices=[('misp', 'MISP Platform'), ('otx', 'AlienVault OTX'), ('virustotal', 'VirusTotal'), ('abuse_ch', 'Abuse.ch'), ('emergingthreats', 'Emerging Threats'), ('talos', 'Cisco Talos'), ('custom', 'Custom Feed'), ('osint', 'Open Source Intelligence')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('update_interval', models.IntegerField(default=3600)),
                ('is_enabled', models.BooleanField(default=True)),
                ('confidence_level', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'threat_feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='source_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='threat_intelligence.threatfeed'),
        ),
        migrations.CreateModel(
            name='ThreatHunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hypothesis', models.TextField()),
                ('hunt_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('data_sources', models.JSONField(default=list)),
                ('search_queries', models.JSONField(default=list)),
                ('findings', models.TextField(blank=True)),
                ('confidence', models.IntegerField(default=50)),
                ('metadata', models.JSONField(default=dict)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('iocs_discovered', models.ManyToManyField(blank=True, related_name='hunts', to='threat_intelligence.indicatorofcompromise')),
            ],
            options={
                'db_table': 'threat_hunts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('ioc', 'IOC Report'), ('malware', 'Malware Analysis'), ('campaign', 'Campaign Analysis'), ('actor', 'Threat Actor Profile'), ('vulnerability', 'Vulnerability Report'), ('general', 'General Intelligence')], max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('confidence', models.IntegerField(default=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('tlp', models.CharField(default='white', max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='reports', to='threat_intelligence.threatcampaign')),
                ('iocs', models.ManyToManyField(blank=True, related_name='reports', to='threat_intelligence.indicatorofcompromise')),
                ('threat_actors', models.ManyToManyField(blank=True, related_name='reports', to='threat_intelligence.threatactor')),
            ],
            options={
                'db_table': 'threat_intelligence_reports',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('partial', 'Partial Match'), ('pattern', 'Pattern Match'), ('behavioral', 'Behavioral Match')], max_length=20)),
                ('matched_value', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_event', models.CharField(blank=True, max_length=255)),
                ('event_data', models.JSONField(default=dict)),
                ('confidence', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed Threat'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='detected', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_intelligence.indicatorofcompromise')),
            ],
            options={
                'db_table': 'threat_matches',
            },
        ),
        migrations.CreateModel(
            name='ThreatResponsePlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(choices=[('ioc_match', 'IOC Match'), ('severity_threshold', 'Severity Threshold'), ('threat_type', 'Threat Type'), ('actor_match', 'Threat Actor Match'), ('manual', 'Manual Trigger')], max_length=20)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_execute', models.BooleanField(default=False)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'threat_response_playbooks',
            },
        ),
        migrations.CreateModel(
            name='ThreatResponseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_actions', models.JSONField(default=list)),
                ('results', models.JSONField(default=dict)),
                ('errors', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_intelligence.threatresponseplaybook')),
            ],
            options={
                'db_table': 'threat_response_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='indicatorofcompromise',
            index=models.Index(fields=['value', 'ioc_type'], name='indicators__value_ae7344_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorofcompromise',
            index=models.Index(fields=['threat_type', 'severity'], name='indicators__threat__91d726_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorofcompromise',
            index=models.Index(fields=['status', 'expires_at'], name='indicators__status_6b1dd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorofcompromise',
            unique_together={('value', 'ioc_type', 'source_feed')},
        ),
        migrations.AddIndex(
            model_name='threatmatch',
            index=models.Index(fields=['source_ip', 'first_seen'], name='threat_matc_source__ba8dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='threatmatch',
            index=models.Index(fields=['status', 'first_seen'], name='threat_matc_status_81c9b3_idx'),
        ),
    ]
