# Generated by Django 5.2.6 on 2025-09-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatLandscapeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('total_iocs', models.IntegerField(default=0)),
                ('active_threats', models.IntegerField(default=0)),
                ('threat_actors', models.IntegerField(default=0)),
                ('active_campaigns', models.IntegerField(default=0)),
                ('critical_threats', models.IntegerField(default=0)),
                ('high_threats', models.IntegerField(default=0)),
                ('threat_distribution', models.JSONField(default=dict)),
                ('geographic_distribution', models.JSONField(default=dict)),
                ('trending_threats', models.JSONField(default=list)),
                ('emerging_actors', models.JSONField(default=list)),
                ('feed_statistics', models.JSONField(default=dict)),
                ('detection_statistics', models.JSONField(default=dict)),
                ('response_statistics', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'threat_landscape_snapshots',
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='ThreatAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('analysis_type', models.CharField(choices=[('malware', 'Malware Analysis'), ('network', 'Network Analysis'), ('behavioral', 'Behavioral Analysis'), ('forensic', 'Digital Forensics'), ('correlation', 'Threat Correlation'), ('attribution', 'Threat Attribution')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('artifacts', models.JSONField(default=list)),
                ('findings', models.TextField(blank=True)),
                ('conclusions', models.TextField(blank=True)),
                ('confidence_level', models.IntegerField(default=50)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_actors', models.ManyToManyField(blank=True, related_name='analysis_sessions', to='threat_intelligence.threatactor')),
                ('related_campaigns', models.ManyToManyField(blank=True, related_name='analysis_sessions', to='threat_intelligence.threatcampaign')),
                ('related_iocs', models.ManyToManyField(blank=True, related_name='analysis_sessions', to='threat_intelligence.indicatorofcompromise')),
            ],
            options={
                'db_table': 'threat_analysis_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ThreatHuntingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('query_type', models.CharField(choices=[('kql', 'Kusto Query Language'), ('sql', 'SQL Query'), ('elasticsearch', 'Elasticsearch Query'), ('splunk', 'Splunk Search'), ('yara', 'YARA Rule'), ('sigma', 'Sigma Rule'), ('regex', 'Regular Expression'), ('custom', 'Custom Logic')], max_length=20)),
                ('query_content', models.TextField()),
                ('data_sources', models.JSONField(default=list)),
                ('threat_types', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('effectiveness_score', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'threat_hunting_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('viz_type', models.CharField(choices=[('threat_map', 'Threat Map'), ('attack_timeline', 'Attack Timeline'), ('actor_network', 'Actor Network'), ('campaign_flow', 'Campaign Flow'), ('ioc_relationships', 'IOC Relationships'), ('threat_trends', 'Threat Trends'), ('geographic_heatmap', 'Geographic Heatmap'), ('kill_chain', 'Kill Chain Visualization')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('data_query', models.TextField(blank=True)),
                ('filters', models.JSONField(default=dict)),
                ('time_range', models.JSONField(default=dict)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'threat_visualizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligenceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('detection_rate', 'Detection Rate'), ('false_positive_rate', 'False Positive Rate'), ('response_time', 'Response Time'), ('threat_coverage', 'Threat Coverage'), ('feed_quality', 'Feed Quality'), ('analyst_productivity', 'Analyst Productivity')], max_length=30)),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='threat_intelligence.threatfeed')),
            ],
            options={
                'db_table': 'threat_intelligence_metrics',
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='threat_inte_metric__ec6b5a_idx'), models.Index(fields=['feed', 'timestamp'], name='threat_inte_feed_id_76a7ab_idx')],
            },
        ),
    ]
