# Generated by Django 5.2.6 on 2025-09-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('alert', 'Alert'), ('user', 'User Activity'), ('system', 'System'), ('financial', 'Financial'), ('other', 'Other')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'timestamp'], name='analytics_m_name_b1e977_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(help_text='Cron expression or presets (daily/hourly)', max_length=100)),
                ('recipients', models.JSONField(help_text='List of recipients (emails/webhooks)')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='analytics.reportdefinition')),
            ],
        ),
    ]
