# Generated by Django 5.2.6 on 2025-09-19 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('grover', 'Grover Search Simulation'), ('qwalk', 'Quantum Walks'), ('fact_perm', 'Factorial Permutation Engine'), ('qdt', 'Quantum Decision Trees'), ('varc', 'Variational Circuits'), ('qbm', 'Quantum Boltzmann Machines'), ('qanneal', 'Quantum Annealing'), ('qentropy', 'Quantum Entropy Pool'), ('qgraph', 'Quantum-Inspired Graph Traversal'), ('qcollapse', 'Quantum State Collapse Simulation')], max_length=64)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
