apiVersion: v1
kind: Secret
metadata:
  name: osrovnet-secrets
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  SECRET_KEY: "ZGphbmdvLWluc2VjdXJlLXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24="
  DATABASE_PASSWORD: "b3Nyb3ZuZXRfcGFzc3dvcmQ="
  REDIS_PASSWORD: "cmVkaXNfcGFzc3dvcmQ="
  SHODAN_API_KEY: "eW91ci1zaG9kYW4tYXBpLWtleS1oZXJl"
  MAXMIND_LICENSE_KEY: "eW91ci1tYXhtaW5kLWxpY2Vuc2Uta2V5LWhlcmU="
  JWT_SECRET: "and0LXNlY3JldC1rZXktZm9yLWF1dGhlbnRpY2F0aW9u"
  ENCRYPTION_KEY: "ZW5jcnlwdGlvbi1rZXktZm9yLXNlbnNpdGl2ZS1kYXRh"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: osrovnet-tls
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: tls-certificates
type: kubernetes.io/tls
data:
  # TLS certificate and key (replace with actual certificates)
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t..."
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t..."
  
---
apiVersion: v1
kind: Secret
metadata:
  name: osrovnet-registry
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJyZWdpc3RyeS5hdG9uaXhjb3JwLmNvbSI6eyJ1c2VybmFtZSI6InJlZ2lzdHJ5X3VzZXIiLCJwYXNzd29yZCI6InJlZ2lzdHJ5X3Bhc3MiLCJhdXRoIjoiY21WbmFYTjBjbmxmZFhObGNqcHlaV2RwYzNSeWVWOXdZWE56In19fQ=="