apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: database-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: cache-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrovnet-logs-pvc
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: logs-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: network-storage
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrovnet-data-pvc
  namespace: osrovnet
  labels:
    app.kubernetes.io/name: osrovnet
    app.kubernetes.io/component: data-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: network-storage
  resources:
    requests:
      storage: 200Gi